server:
  port: 80

rules:
  - !SHARDING
    tables:
      <logic_table_name>: # Logical table name:
        actualDataNodes: # consists of logical data source name plus table name (refer to Inline syntax rules)
        tableStrategy: # Table shards strategy. The same as database shards strategy
          standard:
            shardingColumn: # Sharding column name
            shardingAlgorithmName: # Sharding algorithm name
        keyGenerateStrategy:
          column: # Auto-increment column name. By default, the auto-increment primary key generator is not used.
          keyGeneratorName: # Distributed sequence algorithm name
    defaultDatabaseStrategy:
      standard:
        shardingColumn: # Sharding column name
        shardingAlgorithmName: # Sharding algorithm name
    shardingAlgorithms:
      <sharding_algorithm_name>: # Sharding algorithm name
        type: INLINE
        props:
          algorithm-expression: # INLINE expression
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: # INLINE expression
    keyGenerators:
      <key_generate_algorithm_name> (+): # Distributed sequence algorithm name
        type: # Distributed sequence algorithm type
        props: # Property configuration of distributed sequence algorithm
  - !ENCRYPT
    encryptors:
      <encrypt_algorithm_name> (+): # Encryption and decryption algorithm name
        type: # Encryption and decryption algorithm type
        props: # Encryption and decryption algorithm property configuration
      <encrypt_algorithm_name> (+): # Encryption and decryption algorithm name
        type: # Encryption and decryption algorithm type
    tables:
      <table_name>: # Encryption table name
        columns:
          <column_name> (+): # Encrypt logic column name
            cipher:
              name: # Cipher column name
              encryptorName: # Cipher encrypt algorithm name
            assistedQuery (?):
              name: # Assisted query column name
              encryptorName:  # Assisted query encrypt algorithm name
            likeQuery (?):
              name: # Like query column name
              encryptorName:  # Like query encrypt algorithm name
